config/routes.rb
Laguiltiere2::Application.routes.draw do

  get "homepage/index"
  resources :documents

  root "homepage#index" 

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get '/rates(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  # About section 
  #get "about_the_house", to: 'pages#about_the_house', as: "about_the_house"
  #get "about_the_gardens", to: 'pages#about_the_garden', as: "about_the_garden"
  #get "about_the_caravans", to: 'pages#about_the_caravan', as: "about_the_caravan"

  get "home", to: "pages#home", as: "home"

  get "inside", to: "pages#inside", as: "inside"

  get "contact_us", :controller => "contact_us", :action => :index
  post "contact_us", :controller => "contact_us", :action => :create

  get "rooms", :controller => "rooms", :action => :index

  get "inquiries", :controller => "booking", :action => :index    

  post "inquiries", :controller => "booking", :action => :create    

  get "prices", :controller => "prices", :action => :index  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/document.rb
class Document < ActiveRecord::Base

  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :documentsimages

  # Friendly id is very bugged 
  def self.find(id)
    self.friendly.find(id)
  end
end

app/models/documentsimage.rb
class Documentsimage < ActiveRecord::Base
  belongs_to :document

  mount_uploader :filename, DocumentsUploader
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_event_calendar
end

app/models/page.rb
class Page < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/slider.rb
class Slider < ActiveRecord::Base
  mount_uploader :filename, SliderUploader

end

app/models/user.rb
class User < ActiveRecord::Base
  # Use friendly_id on Users
  extend FriendlyId
  friendly_id :friendify, use: :slugged
  
  # necessary to override friendly_id reserved words
  def friendify
    if username.downcase == "admin"
      "user-#{username}"
    else
      "#{username}"
    end
  end
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  # Pagination
  paginates_per 100
  
  # Validations
  # :username
  validates :username, uniqueness: { case_sensitive: false }
  validates_format_of :username, with: /\A[a-zA-Z0-9]*\z/, on: :create, message: "can only contain letters and digits"
  validates :username, length: { in: 4..10 }
  # :email
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  
  def self.paged(page_number)
    order(admin: :desc, username: :asc).page page_number
  end
  
  def self.search_and_order(search, page_number)
    if search
      where("username LIKE ?", "%#{search.downcase}%").order(
      admin: :desc, username: :asc
      ).page page_number
    else
      order(admin: :desc, username: :asc).page page_number
    end
  end
  
  def self.last_signups(count)
    order(created_at: :desc).limit(count).select("id","username","slug","created_at")
  end
  
  def self.last_signins(count)
    order(last_sign_in_at: 
    :desc).limit(count).select("id","username","slug","last_sign_in_at")
  end
  
  def self.users_count
    where("admin = ? AND locked = ?",false,false).count
  end
end

app/controllers/pages_controller.rb
class PagesController < InheritedResources::Base
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
helpers do
  include CalendarHelper
end
  def index
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_filter :get_site_title

  def index
  end

  private
    def get_site_title
      @title = "La Guiltere - Our rooms"
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(value)
    unless value.nil?
      @title = "#{value} | Laguiltiere"      
    end
  end

end

app/helpers/booking_helper.rb
module BookingHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def month_link(month_date)
    link_to(I18n.localize(month_date, :format => "%B"), {:month => month_date.month, :year => month_date.year})
  end
  
  # custom options for this calendar
  def event_calendar_opts
    { 
      :year => @year,
      :month => @month,
      :event_strips => @event_strips,
      :month_name_text => I18n.localize(@shown_month, :format => "%B %Y"),
      :previous_month_text => "<< " + month_link(@shown_month.prev_month),
      :next_month_text => month_link(@shown_month.next_month) + " >>"    }
  end

  def event_calendar
    # args is an argument hash containing :event, :day, and :options
    calendar event_calendar_opts do |args|
      event = args[:event]
      %(<a href="/events/#{event.id}" title="#{h(event.name)}">#{h(event.name)}</a>)
    end
  end
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/slider_helper.rb
module SliderHelper
  def slider(images)
    output = '';
   
    # TODO; Refactoring  

 
    images.each do |image|
      output += "<div data-src='"
      output += image.filename.to_s
      output += "'>"
      output += "<div class='camera_caption fadeIn'>
                    <div class='container_12'>
                        <div class='row'>
                            <div class='grid_12'>
                                <a href='#' class='s-btn'>Book now!<i class='fa fa-arrow-circle-right'></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>"
    end
    output 
  end
end

app/views/contact/contact_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
   Hello i'm the <b>Contact</b> system on the website :<br />
   <br />
   <br />
   From name : <%= @contact_var['name']; %><br />
   Email : <%= @contact_var['email']; %><br />
   Telephone : <%= @contact_var['telephone']; %><br />
   -------- Message --------<br /><br />
   <%= @contact_var['message']; %>
  </body>
</html>  

app/views/shared/_footer.html.erb
    <div class="container_12">
        <div class="row">
            <div class="grid_12">
                <div class="fright ind-1">
                    <ul class="list-services clearfix">
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#"><i class="fa fa-rss"></i></a></li>
                    </ul>
                </div>
                <div class="fleft ind-1">
                    <a href="#" class="h-underline">La Guiltiere</a> &copy; <span id="copyright-year"></span> &nbsp; | &nbsp; <a href="index-6.html" class="a-hov color-2">Privacy policy</a>
                    <!--{%FOOTER_LINK} -->
                </div>
            </div>
        </div>
    </div>

app/views/shared/_menu.html.erb
    <div class="container_12">
        <div class="row">
            <div class="grid_12">
                <nav>
                    <ul class="sf-menu">
                        <li <% if controller.controller_name == "homepage" %> class="current" <% end %>><%= link_to "Home", root_url %></li>
                
<li> <a href="#">Publication</a>
  <ul>
<% @documents = Document.find(:all) %>
<% @documents.each do |p| %>
   <li <% if controller.controller_name == "documents" %> class="current" <% end %>><%= link_to p.name, document_path(p.slug)%></li>
<% end %> 
  </ul>
</li>
                        <li <% if controller.controller_name == "calendar" %> class="current" <% end %>><%= link_to "Rates", calendar_path %></li>
                        <li <% if controller.controller_name == "booking"%> class="current" <% end %>><%= link_to "Inquiries", inquiries_path %></li>
			<li <% if controller.controller_name == "rooms"%> class="current" <% end %>><%= link_to "Rooms", rooms_path %></li>
                        <li <% if controller.controller_name == "contact_us"%> class="current" <% end %>><%= link_to "Contact",  contact_us_path  %></li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
  
    <%= yield :header_banner %>   